[package]
name = "nas-ws"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.15"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.27.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
strum_macros = "0.24"
strum = { version = "0.24", features = ["derive"] }
base64 = "0.21.0"
gray_matter = "0.2.6"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
rspc = { version = "0.1.3", features = ["axum"] }
vercel_runtime = { version = "0.3.4" }
rand = "0.8.5"
url = "2.3.1"

[[bin]]
name = "nas-ws"
path = "src/bin.rs"

[lib]
path = "src/lib.rs"

[[bin]]
name = "hello"
path = "api/hello.rs"

[[bin]]
name = "parse_mdx"
path = "api/utils/parse_mdx.rs"
